export const styles: any = {
  container: { 
    minHeight: '100vh', 
    width: '100vw', 
    backgroundColor: '#f4f7f6', 
    color: '#333', 
    fontFamily: 'sans-serif',
    display: 'flex', 
    flexDirection: 'column',
    alignItems: 'center', 
    justifyContent: 'flex-start',
    boxSizing: 'border-box'
  },
  center: { textAlign: 'center', padding: '100px' },
  card: { 
    width: '100%',
    maxWidth: '400px', 
    margin: '60px auto', 
    padding: '40px', 
    backgroundColor: '#fff', 
    borderRadius: '12px', 
    textAlign: 'center', 
    boxShadow: '0 4px 12px rgba(0,0,0,0.1)',
    boxSizing: 'border-box'
  },
  form: { display: 'flex', flexDirection: 'column', gap: '15px' },
  input: { padding: '12px', borderRadius: '6px', border: '1px solid #ddd', fontSize: '16px', width: '100%', boxSizing: 'border-box' },
  primaryBtn: { width: '100%', padding: '12px', backgroundColor: '#1877f2', color: '#fff', border: 'none', borderRadius: '6px', cursor: 'pointer', fontWeight: 'bold', fontSize: '16px', marginTop: '10px' },
  textBtn: { marginTop: '15px', background: 'none', border: 'none', color: '#1877f2', cursor: 'pointer', textDecoration: 'underline' },
  googleBtn: { width: '100%', padding: '12px', backgroundColor: '#fff', color: '#555', border: '1px solid #ddd', borderRadius: '6px', cursor: 'pointer', fontWeight: 'bold' },
  divider: { margin: '20px 0', color: '#aaa', fontSize: '14px' },
  errorText: { color: 'red', fontSize: '12px', textAlign: 'left', margin: 0 },
  subText: { color: '#666', fontSize: '14px', marginBottom: '20px', lineHeight: '1.5' },
  dashboard: { 
    width: '100%',
    maxWidth: '1200px', 
    padding: '30px',
    boxSizing: 'border-box' 
  },
  header: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '30px' },
  title: { color: '#1c1e21', margin: 0 },
  inviteBox: { backgroundColor: '#e7f3ff', padding: '10px 15px', borderRadius: '8px', color: '#1877f2', marginBottom: '15px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
  reissueBtn: { marginLeft: '10px', padding: '4px 8px', backgroundColor: '#fff', color: '#1877f2', border: '1px solid #1877f2', borderRadius: '4px', cursor: 'pointer' },
  logoutBtn: { backgroundColor: '#fa3e3e', color: '#fff', border: 'none', padding: '10px 20px', borderRadius: '6px', cursor: 'pointer' },
  iconBtn: { background: 'none', border: 'none', fontSize: '24px', cursor: 'pointer', padding: '5px' },
  settingsCard: { backgroundColor: '#fff', padding: '30px', borderRadius: '12px', boxShadow: '0 2px 8px rgba(0,0,0,0.05)', maxWidth: '600px', margin: '0 auto' },
  deleteAccountBtn: { backgroundColor: '#fa3e3e', color: '#fff', border: 'none', padding: '12px 20px', borderRadius: '6px', cursor: 'pointer', fontWeight: 'bold', marginTop: '10px' },
  sectionRow: { display: 'flex', gap: '30px', flexWrap: 'wrap', justifyContent: 'center' },
  tableHalf: { flex: '1', minWidth: '400px', maxWidth: '585px' },
  actionRow: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '10px' },
  csvBtn: { backgroundColor: '#10B981', color: '#fff', border: 'none', padding: '8px 16px', borderRadius: '6px', cursor: 'pointer' },
  tableCard: { backgroundColor: '#fff', borderRadius: '12px', boxShadow: '0 2px 8px rgba(0,0,0,0.05)', overflow: 'hidden' },
  table: { width: '100%', borderCollapse: 'collapse' },
  tableHeader: { backgroundColor: '#f8f9fa' },
  td: { padding: '12px', borderBottom: '1px solid #eee' },
  deleteBtn: { backgroundColor: '#fff', color: '#fa3e3e', border: '1px solid #fa3e3e', padding: '4px 8px', borderRadius: '4px', cursor: 'pointer' }
};
